# ################################
# Model: Speaker Verification Baseline
# Authors: Hwidong Na 2020
#          Mirco Ravanelli 2020
# ################################

seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder: /media/absp/4E897AE46CE3ABFA/IMSV/I-MSV-DATA
output_folder: /media/absp/4E897AE46CE3ABFA/IMSV/results/imsv_test/speaker_verification_ecapa_big_trained
save_folder: !ref <output_folder>/save
device: 'cuda:0'

# Verification file split scraped from Enr Files:
verification_file: /media/absp/4E897AE46CE3ABFA/IMSV/I-MSV-DATA/test_divided/IMSV_public_test_aa
# Here, the pretrained embedding model trained with train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml
# is downloaded from the speechbrain HuggingFace repository.
# However, a local path pointing to a directory containing your checkpoints may also be specified
# instead (see pretrainer below)
pretrain_path: /media/absp/4E897AE46CE3ABFA/IMSV/results/ecapa_augment/1986/save/CKPT+2022-09-15+01-11-08+00

# csv files
train_data: !ref <save_folder>/train.csv
enrol_data: !ref <save_folder>/enrol.csv
test_data: !ref <save_folder>/test.csv
test_enrol_data: !ref <save_folder>/hidden_test.csv
test_test_data: !ref <save_folder>/hidden_enrol.csv
test: True # test = True if no labels provided in CSV File

batch_size: 16
# Score norm utilises the training data to create cohorts
# score_norm: s-norm  # z-norm t-norm s-norm (uncomment to enable it)
cohort_size: 100 # amount of imposter utterances in normalization cohort
n_train_snts: 2000 # used for normalization stats

# Feature parameters
n_mels: 80
# left_frames: 0
# right_frames: 0
# deltas: False

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

enrol_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: 192

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrain_path>/embedding_model.ckpt
